services:
  - type: web
    name: traffic-backend
    plan: free
    runtime: docker
    dockerfilePath: ./smart-traffic-simulator-backend/Dockerfile
    dockerContext: ./smart-traffic-simulator-backend/
    envVars:
      - key: PORT
        value: 8080
    autoDeployTrigger: checksPass

  - type: web
    name: traffic-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./smart-traffic-simulator-frontend/dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: traffic-backend
          property: host
    autoDeployTrigger: checksPass